# Generated by Django 4.2.28 on 2026-02-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='experts',
            new_name='excerpts',
        ),
    ]
